### ISSUE TITLE
Probably an integer overflow vulnerability

### ISSUE THREAD

**Issue by HongxuChen** [cesanta/mjs#57]
With the driver program mentioned in #54 , our fuzzing tool find an memcpy related segfault that may result from an integer overflow.

Input file:
[w04_000028,sig:6,Splice:73:102,src:w01_000499.txt](https://github.com/cesanta/mjs/files/1503156/w04_000028.sig.6.Splice.73.102.src.w01_000499.txt)

when using address sanitizer, it dumps:

```
github/nsp > ../mjs_debug_asan w04_000028,sig:6,Splice:73:102,src:w01_000499.txt                                                                                                                  
=================================================================
==17140==ERROR: AddressSanitizer: negative-size-param: (size=-2)
    #0 0x4bbb6b  (/home/hongxu/FUSE/tests/mjs/github/mjs_debug_asan+0x4bbb6b)
    #1 0x53c2a1  (/home/hongxu/FUSE/tests/mjs/github/mjs_debug_asan+0x53c2a1)
    #2 0x53a1dc  (/home/hongxu/FUSE/tests/mjs/github/mjs_debug_asan+0x53a1dc)
    #3 0x56cf71  (/home/hongxu/FUSE/tests/mjs/github/mjs_debug_asan+0x56cf71)
    #4 0x5411fd  (/home/hongxu/FUSE/tests/mjs/github/mjs_debug_asan+0x5411fd)
    #5 0x54049b  (/home/hongxu/FUSE/tests/mjs/github/mjs_debug_asan+0x54049b)
    #6 0x545ad5  (/home/hongxu/FUSE/tests/mjs/github/mjs_debug_asan+0x545ad5)
    #7 0x541a1f  (/home/hongxu/FUSE/tests/mjs/github/mjs_debug_asan+0x541a1f)
    #8 0x5404ee  (/home/hongxu/FUSE/tests/mjs/github/mjs_debug_asan+0x5404ee)
    #9 0x51bd97  (/home/hongxu/FUSE/tests/mjs/github/mjs_debug_asan+0x51bd97)
    #10 0x51baee  (/home/hongxu/FUSE/tests/mjs/github/mjs_debug_asan+0x51baee)
    #11 0x56c88e  (/home/hongxu/FUSE/tests/mjs/github/mjs_debug_asan+0x56c88e)
    #12 0x52f99d  (/home/hongxu/FUSE/tests/mjs/github/mjs_debug_asan+0x52f99d)
    #13 0x535d61  (/home/hongxu/FUSE/tests/mjs/github/mjs_debug_asan+0x535d61)
    #14 0x532b51  (/home/hongxu/FUSE/tests/mjs/github/mjs_debug_asan+0x532b51)
    #15 0x5327d3  (/home/hongxu/FUSE/tests/mjs/github/mjs_debug_asan+0x5327d3)
    #16 0x50ba16  (/home/hongxu/FUSE/tests/mjs/github/mjs_debug_asan+0x50ba16)
    #17 0x7f9940b6d82f  (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #18 0x419b68  (/home/hongxu/FUSE/tests/mjs/github/mjs_debug_asan+0x419b68)
0x607000000020 is located 0 bytes inside of 69-byte region [0x607000000020,0x607000000065)
allocated by thread T0 here:
    #0 0x4d21e8  (/home/hongxu/FUSE/tests/mjs/github/mjs_debug_asan+0x4d21e8)
    #1 0x56cdd4  (/home/hongxu/FUSE/tests/mjs/github/mjs_debug_asan+0x56cdd4)
    #2 0x5411fd  (/home/hongxu/FUSE/tests/mjs/github/mjs_debug_asan+0x5411fd)
    #3 0x54049b  (/home/hongxu/FUSE/tests/mjs/github/mjs_debug_asan+0x54049b)
    #4 0x545ad5  (/home/hongxu/FUSE/tests/mjs/github/mjs_debug_asan+0x545ad5)
    #5 0x541a1f  (/home/hongxu/FUSE/tests/mjs/github/mjs_debug_asan+0x541a1f)
    #6 0x5404ee  (/home/hongxu/FUSE/tests/mjs/github/mjs_debug_asan+0x5404ee)
    #7 0x51bd97  (/home/hongxu/FUSE/tests/mjs/github/mjs_debug_asan+0x51bd97)
    #8 0x51baee  (/home/hongxu/FUSE/tests/mjs/github/mjs_debug_asan+0x51baee)
    #9 0x56c88e  (/home/hongxu/FUSE/tests/mjs/github/mjs_debug_asan+0x56c88e)
    #10 0x52f99d  (/home/hongxu/FUSE/tests/mjs/github/mjs_debug_asan+0x52f99d)
    #11 0x535d61  (/home/hongxu/FUSE/tests/mjs/github/mjs_debug_asan+0x535d61)
    #12 0x532b51  (/home/hongxu/FUSE/tests/mjs/github/mjs_debug_asan+0x532b51)
    #13 0x5327d3  (/home/hongxu/FUSE/tests/mjs/github/mjs_debug_asan+0x5327d3)
    #14 0x50ba16  (/home/hongxu/FUSE/tests/mjs/github/mjs_debug_asan+0x50ba16)
    #15 0x7f9940b6d82f  (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
SUMMARY: AddressSanitizer: negative-size-param (/home/hongxu/FUSE/tests/mjs/github/mjs_debug_asan+0x4bbb6b)
==17140==ABORTING
[1]    17140 abort      ../mjs_debug_asan w04_000028,sig:6,Splice:73:102,src:w01_000499.txt
```

a gdb result:

```
gdb$ run w04_000028,sig:6,Splice:73:102,src:w01_000499
Starting program: /home/hongxu/FUSE/tests/mjs/github/mjs_debug w04_000028,sig:6,Splice:73:102,src:w01_000499
Program received signal SIGSEGV, Segmentation fault.
__memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:266
266     ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S: No such file or directory.
gdb$ bt
#0  __memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:266
#1  0x000000000041089d in embed_string (m=0x62b0c0, offset=0xa3, p=0x62bb30 "&\n 'f t@peof unlefized === 'undefined';\n\n && typeof\006print === 'fore", len=0xfffffffffffffffe, flags=0x1) at ../mjs.c:13733
#2  0x000000000040fcaa in mjs_mk_string (mjs=0x62b010, p=0x62bb30 "&\n 'f t@peof unlefized === 'undefined';\n\n && typeof\006print === 'fore", len=0xfffffffffffffffe, copy=0x1) at ../mjs.c:13314
#3  0x0000000000421df1 in frozen_cb (data=0x62b900, name=0x62b99c "e\": \"1\211", ' ' <repeats 14 times>, "\\\\\\\\i", '\\' <repeats 46 times>, "\307\\\"\\\\\\\\\"d\" null], \"e\": \"1\\n2\"}", name_len=0x1, path=0x7fffffffb390 ".e", token=0x7fffffffb190) at ../mjs.c:11588
#4  0x0000000000412720 in parse_string (f=0x7fffffffb370) at ../mjs.c:5725
#5  0x000000000041230c in parse_value (f=0x7fffffffb370) at ../mjs.c:5811
#6  0x000000000041380e in parse_pair (f=0x7fffffffb370) at ../mjs.c:5874
#7  0x00000000004128d4 in parse_object (f=0x7fffffffb370) at ../mjs.c:5886
#8  0x000000000041233c in parse_value (f=0x7fffffffb370) at ../mjs.c:5814
#9  0x0000000000406436 in doit (f=0x7fffffffb370) at ../mjs.c:5899
#10 0x0000000000406382 in json_walk (json_string=0x62b99a "{\"e\": \"1\211", ' ' <repeats 14 times>, "\\\\\\\\i", '\\' <repeats 46 times>, "\307\\\"\\\\\\\\\"d\" null], \"e\": \"1\\n2\"}", json_string_length=0x68, callback=0x421d20 <frozen_cb>, callback_data=0x62b900) at ../mjs.c:6275
#11 0x0000000000421c3f in mjs_json_parse (mjs=0x62b010, str=0x62b99a "{\"e\": \"1\211", ' ' <repeats 14 times>, "\\\\\\\\i", '\\' <repeats 46 times>, "\307\\\"\\\\\\\\\"d\" null], \"e\": \"1\\n2\"}", len=0x68, res=0x7fffffffb550) at ../mjs.c:11681
#12 0x000000000040b975 in mjs_op_json_parse (mjs=0x62b010) at ../mjs.c:11730
#13 0x000000000040e3d2 in mjs_execute (mjs=0x62b010, off=0x0, res=0x7fffffffb8d8) at ../mjs.c:9282
#14 0x000000000040cf4e in mjs_exec_internal (mjs=0x62b010, path=0x4248e7 "<stdin>", src=0x62c250 '\\' <repeats 114 times>, "O\\\\\\\\\\\\\\\\\\\\P", '\\' <repeats 62 times>, "O", '\\' <repeats 11 times>..., generate_jsc=0x0, res=0x0) at ../mjs.c:9489
#15 0x000000000040ce94 in mjs_exec (mjs=0x62b010, src=0x62c250 '\\' <repeats 114 times>, "O\\\\\\\\\\\\\\\\\\\\P", '\\' <repeats 62 times>, "O", '\\' <repeats 11 times>..., res=0x0) at ../mjs.c:9496
#16 0x00000000004015e5 in main (argc=0x2, argv=0x7fffffffba68) at ../driver.c:42
```

We think that `len=0xfffffffffffffffe` should not happen in a common scenario, which seems from an integer overflow inside `frozen_cb`.

Footnote: we are somewhat lost why memcpy (with avx enabled) failed since `0xfffffffffffffffe` is valid for a `size_t` type (2^64-2) however the sanitizer tells that the value is -2.

**Comment by dimonomid** [comment]
Resolved with https://github.com/cesanta/mjs/commit/db0e2d696be94df098ca42e1e417cf0c500014a0
