### ISSUE TITLE
null pointer error

### ISSUE THREAD

**Issue by HongxuChen** [cesanta/mjs#64]
This is a null pointer error found in a commit prior to 15/Dec/2017 however still occured in d5bbef37cb2d382cea040413ff4c273fa57e5ba8, it results in an assertion error.

```
gdb$ run submit/w01_000000,sig:6,Splice:13:16,src:w04_000517.txt
Starting program: /home/hongxu/FUSE/tests/mjs-ins/mjs_debug_main_FOT-new.out submit/w01_000000,sig:6,Splice:13:16,src:w04_000517.txt
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
mjs_debug_main_FOT-new.out: ../mjs/mjs.c:8515: int mjs_getretvalpos(struct mjs *): Assertion `ppos != NULL && mjs_is_number(*ppos)' failed.
Program received signal SIGABRT, Aborted.
0x00007ffff6ef9428 in __GI_raise (sig=sig@entry=0x6) at ../sysdeps/unix/sysv/linux/raise.c:54
54      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
gdb$ bt
#0  0x00007ffff6ef9428 in __GI_raise (sig=sig@entry=0x6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff6efb02a in __GI_abort () at abort.c:89
#2  0x00007ffff6ef1bd7 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x5c5040 <.str> "ppos != NULL && mjs_is_number(*ppos)", file=file@entry=0x5c2f80 <.str> "../mjs/mjs.c", line=line@entry=0x2143, function=function@entry=0x5c50a0 <__PRETTY_FUNCTION__.mjs_getretvalpos> "int mjs_getretvalpos(struct mjs *)") at assert.c:92
#3  0x00007ffff6ef1c82 in __GI___assert_fail (assertion=0x5c5040 <.str> "ppos != NULL && mjs_is_number(*ppos)", file=0x5c2f80 <.str> "../mjs/mjs.c", line=0x2143, function=0x5c50a0 <__PRETTY_FUNCTION__.mjs_getretvalpos> "int mjs_getretvalpos(struct mjs *)") at assert.c:101
#4  0x0000000000541e48 in mjs_getretvalpos (mjs=0x615000000080) at ../mjs/mjs.c:8515
#5  0x0000000000542006 in mjs_arg (mjs=0x615000000080, arg_index=0x0) at ../mjs/mjs.c:8531
#6  0x0000000000548152 in mjs_execute (mjs=0x615000000080, off=0x0, res=0x7fffffffb3e0) at ../mjs/mjs.c:9503
#7  0x000000000054357d in mjs_exec_internal (mjs=0x615000000080, path=0x7fffffffc079 "submit/w01_000000,sig:6,Splice:13:16,src:w04_000517.txt", src=0x621000001500 "/* *B*.* BEGIN CIC*NSE B\377\377\377\177 ...\016........ikn: NPL 1.1/GPL ", '-' <repeats 142 times>..., generate_jsc=0x0, res=0x7fffffffb560) at ../mjs/mjs.c:9706
#8  0x00000000005439a9 in mjs_exec_file (mjs=0x615000000080, path=0x7fffffffc079 "submit/w01_000000,sig:6,Splice:13:16,src:w04_000517.txt", res=0x7fffffffb6a0) at ../mjs/mjs.c:9729
#9  0x000000000054c982 in main (argc=0x2, argv=0x7fffffffb948) at ../mjs/mjs.c:12009
```

[w01_000000,sig:6,Splice:13:16,src:w04_000517.txt](https://github.com/cesanta/mjs/files/1585622/w01_000000.sig.6.Splice.13.16.src.w04_000517.txt)

**Comment by HongxuChen** [comment]
[w02_000013,sig:6,Splice:12:16,src:w04_000524.txt](https://github.com/cesanta/mjs/files/1585659/w02_000013.sig.6.Splice.12.16.src.w04_000524.txt)
